/* Пестицидлар (ўсимликларни ҳимоя қилиш воситалари) намунавий базаси.
 *
 * ⚠️ ДИҚҚАТ: бу — НАМУНАВИЙ (демонстрацион) маълумотлар. Ўзбекистон
 * Республикасининг РАСМИЙ давлат рўйхати ЭМАС. Ҳақиқий рўйхат рақамлари,
 * муддатлар ва меъёрлар расмий манбадан текширилиши шарт.
 *
 * Ҳақиқий базага алмаштириш: шу файлдаги window.PREPARATLAR массивини
 * расмий рўйхат маълумотлари билан тўлдиринг (тузилиш ўзгармайди).
 *
 * type: insecticide | fungicide | herbicide | acaricide | biopreparat | defoliant
 */
window.PREPARATLAR = [
  { trade_uz: "Актеллик, 50% э.к.", trade_ru: "Актеллик, 50% к.э.", ai: "Пиримифос-метил, 500 г/л", type: "insecticide", company: "Syngenta (Швейцария)", crop_uz: "Ғўза, сабзавот", crop_ru: "Хлопчатник, овощи", target_uz: "Ўргимчаккана, шира, оқ пашша", target_ru: "Клещ, тля, белокрылка", rate: "1,0–1,5 л/га", solution: "300–600 л/га", reg: "namuna-001", expiry: "2028", hazard: "II (ўртача хавфли)", waiting: "20 кун" },
  { trade_uz: "Карате Зеон, 5% с.к.", trade_ru: "Карате Зеон, 5% к.с.", ai: "Лямбда-цигалотрин, 50 г/л", type: "insecticide", company: "Syngenta (Швейцария)", crop_uz: "Ғўза, буғдой", crop_ru: "Хлопчатник, пшеница", target_uz: "Тунлам, битлар, трипс", target_ru: "Совка, клопы, трипс", rate: "0,2–0,4 л/га", solution: "300 л/га", reg: "namuna-002", expiry: "2027", hazard: "II", waiting: "30 кун" },
  { trade_uz: "Конфидор, 20% с.к.", trade_ru: "Конфидор, 20% в.р.к.", ai: "Имидаклоприд, 200 г/л", type: "insecticide", company: "Bayer (Германия)", crop_uz: "Ғўза, картошка, сабзавот", crop_ru: "Хлопчатник, картофель, овощи", target_uz: "Шира, оқ пашша, колорадо қўнғизи", target_ru: "Тля, белокрылка, колорадский жук", rate: "0,2–0,3 л/га", solution: "300 л/га", reg: "namuna-003", expiry: "2028", hazard: "II", waiting: "28 кун" },
  { trade_uz: "Данадим, 40% э.к.", trade_ru: "Данадим, 40% к.э.", ai: "Диметоат, 400 г/л", type: "insecticide", company: "Cheminova (Дания)", crop_uz: "Ғўза, дон экинлари", crop_ru: "Хлопчатник, зерновые", target_uz: "Шира, каналар, трипс", target_ru: "Тля, клещи, трипс", rate: "1,0–1,5 л/га", solution: "300 л/га", reg: "namuna-004", expiry: "2026", hazard: "II", waiting: "30 кун" },
  { trade_uz: "Вертимек, 1,8% э.к.", trade_ru: "Вертимек, 1,8% к.э.", ai: "Абамектин, 18 г/л", type: "acaricide", company: "Syngenta (Швейцария)", crop_uz: "Сабзавот, мевали дарахтлар", crop_ru: "Овощи, плодовые", target_uz: "Ўргимчаккана, трипс", target_ru: "Паутинный клещ, трипс", rate: "0,4–0,8 л/га", solution: "600–1000 л/га", reg: "namuna-005", expiry: "2027", hazard: "II", waiting: "28 кун" },
  { trade_uz: "Ниссоран, 10% н.кук.", trade_ru: "Ниссоран, 10% с.п.", ai: "Гекситиазокс, 100 г/кг", type: "acaricide", company: "Nippon Soda (Япония)", crop_uz: "Мевали дарахтлар, ток", crop_ru: "Плодовые, виноград", target_uz: "Ўргимчаккана (тухум ва личинка)", target_ru: "Клещ (яйца и личинки)", rate: "0,3–0,6 кг/га", solution: "1000 л/га", reg: "namuna-006", expiry: "2028", hazard: "III (кам хавфли)", waiting: "30 кун" },
  { trade_uz: "Тилт, 25% э.к.", trade_ru: "Тилт, 25% к.э.", ai: "Пропиконазол, 250 г/л", type: "fungicide", company: "Syngenta (Швейцария)", crop_uz: "Буғдой, арпа", crop_ru: "Пшеница, ячмень", target_uz: "Занг, ун-шудринг, септориоз", target_ru: "Ржавчина, мучнистая роса, септориоз", rate: "0,5 л/га", solution: "300 л/га", reg: "namuna-007", expiry: "2027", hazard: "III", waiting: "40 кун" },
  { trade_uz: "Фоликур, 25% э.к.", trade_ru: "Фоликур, 25% к.э.", ai: "Тебуконазол, 250 г/л", type: "fungicide", company: "Bayer (Германия)", crop_uz: "Буғдой, ток", crop_ru: "Пшеница, виноград", target_uz: "Ун-шудринг, занг", target_ru: "Мучнистая роса, ржавчина", rate: "0,5–1,0 л/га", solution: "300 л/га", reg: "namuna-008", expiry: "2028", hazard: "III", waiting: "30 кун" },
  { trade_uz: "Ридомил Голд МЦ, 68% н.кук.", trade_ru: "Ридомил Голд МЦ, 68% с.п.", ai: "Металаксил-М 40 + манкоцеб 640 г/кг", type: "fungicide", company: "Syngenta (Швейцария)", crop_uz: "Картошка, узум, сабзавот", crop_ru: "Картофель, виноград, овощи", target_uz: "Фитофтороз, милдью", target_ru: "Фитофтороз, милдью", rate: "2,5 кг/га", solution: "600 л/га", reg: "namuna-009", expiry: "2027", hazard: "III", waiting: "20 кун" },
  { trade_uz: "Олтингугурт (коллоид)", trade_ru: "Сера коллоидная", ai: "Олтингугурт, 800 г/кг", type: "fungicide", company: "Турли ишлаб чиқарувчилар", crop_uz: "Ток, мевали дарахтлар", crop_ru: "Виноград, плодовые", target_uz: "Ун-шудринг, каналар", target_ru: "Мучнистая роса, клещи", rate: "6–8 кг/га", solution: "1000 л/га", reg: "namuna-010", expiry: "—", hazard: "IV (амалда хавфсиз)", waiting: "1 кун" },
  { trade_uz: "Раундап, 36% сув.эр.", trade_ru: "Раундап, 36% в.р.", ai: "Глифосат, 360 г/л", type: "herbicide", company: "Bayer/Monsanto", crop_uz: "Экишдан олдин, боғ оралиғи", crop_ru: "До посева, междурядья", target_uz: "Бир ва кўп йиллик бегона ўтлар (ялпи)", target_ru: "Одно- и многолетние сорняки (сплошное)", rate: "2,0–4,0 л/га", solution: "200 л/га", reg: "namuna-011", expiry: "2028", hazard: "III", waiting: "—" },
  { trade_uz: "Флуроксипир (Flurog 40), э.к.", trade_ru: "Флуроксипир (Flurog 40), к.э.", ai: "Флуроксипир, 400 г/л", type: "herbicide", company: "AGRO-SERVICE-TORG (Ўзбекистон)", crop_uz: "Кузги буғдой", crop_ru: "Озимая пшеница", target_uz: "Икки паллали бегона ўтлар", target_ru: "Двудольные сорняки", rate: "0,5 л/га", solution: "300 л/га", reg: "namuna-012", expiry: "2029", hazard: "III", waiting: "60 кун" },
  { trade_uz: "Пума Супер, 7,5% э.в.с.", trade_ru: "Пума Супер, 7,5% э.м.в.", ai: "Феноксапроп-П-этил, 69 г/л", type: "herbicide", company: "Bayer (Германия)", crop_uz: "Буғдой", crop_ru: "Пшеница", target_uz: "Бир йиллик бошоқли бегона ўтлар", target_ru: "Однолетние злаковые сорняки", rate: "0,8–1,0 л/га", solution: "300 л/га", reg: "namuna-013", expiry: "2027", hazard: "III", waiting: "—" },
  { trade_uz: "Стомп, 33% э.к.", trade_ru: "Стомп, 33% к.э.", ai: "Пендиметалин, 330 г/л", type: "herbicide", company: "BASF (Германия)", crop_uz: "Ғўза, сабзавот", crop_ru: "Хлопчатник, овощи", target_uz: "Бир йиллик бегона ўтлар (тупроқ бўйича)", target_ru: "Однолетние сорняки (почвенный)", rate: "3,0–6,0 л/га", solution: "300 л/га", reg: "namuna-014", expiry: "2028", hazard: "III", waiting: "—" },
  { trade_uz: "Децис Профи, 25% сув.дисп.гран.", trade_ru: "Децис Профи, 25% в.д.г.", ai: "Дельтаметрин, 250 г/кг", type: "insecticide", company: "Bayer (Германия)", crop_uz: "Ғўза, сабзавот, дон", crop_ru: "Хлопчатник, овощи, зерно", target_uz: "Тунлам, битлар, трипс", target_ru: "Совка, клопы, трипс", rate: "0,03–0,05 кг/га", solution: "300 л/га", reg: "namuna-015", expiry: "2028", hazard: "II", waiting: "30 кун" },
  { trade_uz: "Проклейм, 5% сув.дисп.гран.", trade_ru: "Проклейм, 5% в.д.г.", ai: "Эмамектин бензоат, 50 г/кг", type: "insecticide", company: "Syngenta (Швейцария)", crop_uz: "Сабзавот, ғўза", crop_ru: "Овощи, хлопчатник", target_uz: "Тунлам ва капалак личинкалари", target_ru: "Гусеницы совок и молей", rate: "0,3–0,4 кг/га", solution: "400 л/га", reg: "namuna-016", expiry: "2027", hazard: "II", waiting: "14 кун" },
  { trade_uz: "Боверин (биопрепарат)", trade_ru: "Боверин (биопрепарат)", ai: "Beauveria bassiana", type: "biopreparat", company: "Маҳаллий биолабораториялар", crop_uz: "Ғўза, сабзавот", crop_ru: "Хлопчатник, овощи", target_uz: "Тунлам, оқ пашша (биологик)", target_ru: "Совка, белокрылка (биологический)", rate: "2–3 кг/га", solution: "300 л/га", reg: "namuna-017", expiry: "—", hazard: "IV", waiting: "—" },
  { trade_uz: "Битоксибациллин", trade_ru: "Битоксибациллин", ai: "Bacillus thuringiensis", type: "biopreparat", company: "Маҳаллий биолабораториялар", crop_uz: "Сабзавот, мевали дарахтлар", crop_ru: "Овощи, плодовые", target_uz: "Капалак личинкалари (биологик)", target_ru: "Гусеницы чешуекрылых (биологический)", rate: "2–3 кг/га", solution: "400 л/га", reg: "namuna-018", expiry: "—", hazard: "IV", waiting: "5 кун" },
  { trade_uz: "Дропп, 50% н.кук.", trade_ru: "Дропп, 50% с.п.", ai: "Тидиазурон, 500 г/кг", type: "defoliant", company: "Bayer (Германия)", crop_uz: "Ғўза (дефолиация)", crop_ru: "Хлопчатник (дефолиация)", target_uz: "Барг тўкиш (терим олди)", target_ru: "Опадение листьев (перед сбором)", rate: "0,15–0,2 кг/га", solution: "200 л/га", reg: "namuna-019", expiry: "2027", hazard: "III", waiting: "—" },
  { trade_uz: "Топаз, 10% э.к.", trade_ru: "Топаз, 10% к.э.", ai: "Пенконазол, 100 г/л", type: "fungicide", company: "Syngenta (Швейцария)", crop_uz: "Ток, мевали, сабзавот", crop_ru: "Виноград, плодовые, овощи", target_uz: "Ун-шудринг", target_ru: "Мучнистая роса", rate: "0,3–0,5 л/га", solution: "600–1000 л/га", reg: "namuna-020", expiry: "2028", hazard: "III", waiting: "20 кун" },
];
